### ISSUE TITLE
Create hreflang with rewrites

### ISSUE THREAD

**Issue by axevir** [tzyganu/CmsRewrites#2]
Is there a way to get the rewrite urls programmatically? What I want to do is to create hreflang attributes for each page linking to all other stores. I found a solution to create the urls for products and categories, but atm I am not able to do it properly for cms pages. Can I use your extension to loop through the stores and get the translated url keys for cms pages, once I created them in Magento Admin?
Thanks in advance!

**Comment by tzyganu** [comment]
@axevir That's not in the scope of the extension. You can use the extension to generate your url's but how you use them is your problem.
